services:
  # --------------------------------------------------
  # PostgreSQL Database
  # --------------------------------------------------
  db:
    image: postgres:17-alpine
    container_name: skill-sheet-db
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-user}
      POSTGRES_DB: ${DB_DATABASE:-app}
    ports:
      - '${DB_PORT:-55432}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-user}']
      interval: 10s
      timeout: 5s
      retries: 5

  # --------------------------------------------------
  # Frontend (Next.js)
  # --------------------------------------------------
  frontend:
    build:
      dockerfile: ./.docker/Dockerfile
      context: ./
    command: npm run dev:debug
    volumes:
      - ./:/app:delegated
      - frontend-nodemodules-volume:/app/node_modules/
    env_file:
      - .env
    ports:
      - ${_DOCKER_COMPOSE_HOST_PORT_FRONTEND:-13020}:3000 # for nextjs
      - ${_DOCKER_COMPOSE_HOST_PORT_FRONTEND_DEBUG:-19229}:9229 # for debug
      - ${_DOCKER_COMPOSE_HOST_PORT_FRONTEND_SECOND_DEBUG:-19230}:9230 # for debug port
    depends_on:
      db:
        condition: service_healthy

volumes:
  frontend-nodemodules-volume:
  postgres-data:
